In [6]:
import numpy as np
a=[]
b = int(input("Enter the size of elements"))
for i in range(b):
    val1 = int(input("Enter the number"))
    a.append(val1)
arr = np.array(a)
for i in range(arr.size):
    print(arr[i])
    

Enter the size of elements3
Enter the number1
Enter the number2
Enter the number3
1
2
3


In [8]:
import numpy as np
a=[]
sum = 0
b = int(input("Enter the size of elements"))
for i in range(b):
    val1 = int(input("Enter the number"))
    a.append(val1)
arr = np.array(a)
for i in range(arr.size):
    print(arr[i])
    sum = sum + arr[i]
print("sum of array elements=",sum)
arr1 = arr[2:4]
print(arr1)

Enter the size of elements4
Enter the number1
Enter the number2
Enter the number3
Enter the number4
1
2
3
4
sum of array elements= 10
[3 4]


# Reshape


In [10]:
import numpy as np
arr = np.random.randint(1,100,12)
arr

array([49, 87, 49, 73, 42, 55, 87, 50, 32, 33,  9, 32])

In [11]:
arr.shape

(12,)

In [19]:
arr.reshape(3,4)
arr.ndim

1

In [16]:
arr.reshape(6,2)
arr.ndim

1

In [17]:
arr.ndim

1

In [25]:
import numpy as np
arr = np.random.randint(1,100,12)
arr.reshape(1,4,3)

array([[[86, 16, 92],
        [36, 66, 87],
        [58, 54, 45],
        [ 1, 71, 62]]])

In [22]:
arr.ndim

1

In [26]:
arr.dtype

dtype('int32')

In [1]:
import numpy as np
arr = np.array([[4,5,6],[8,7,6],[1,2,2]])
arr


array([[4, 5, 6],
       [8, 7, 6],
       [1, 2, 2]])

In [5]:
b=arr[1:3,1:3]
b

array([[7, 6],
       [2, 2]])

In [15]:
import numpy as np
#np.random.seed(111) #seed function se hame har baar output same milega instead of random output value
a = np.random.randint(1,500,30).reshape(6,5)


In [16]:
a

array([[174, 454, 335,  32, 345],
       [455,  14,  51, 236, 471],
       [325, 484, 158, 232, 394],
       [171, 404,  98, 423,  60],
       [345, 486, 261, 274,  75],
       [492, 140, 178, 104, 345]])

In [17]:
b=a[3:6,2:6]
b

array([[ 98, 423,  60],
       [261, 274,  75],
       [178, 104, 345]])

# ***Transpose matrix***

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[8,9,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 3]])

In [3]:
arr.T

array([[1, 4, 8],
       [2, 5, 9],
       [3, 6, 3]])

# Identity matrix

In [10]:
import numpy as np
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Agregation function

In [15]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[8,9,10]])
arr.max()

10

In [16]:
arr.min()

1

# Argument maximum (argmax)


In [17]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[10,45,26]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 45, 26]])

In [19]:
arr.argmax()

7

In [20]:
arr.argmin()

0

In [36]:
n = 5 
i = 1
while(i<=n):
    j=1
    while(j<=i):
        print('*',end=' ')
        j=j+1
    print()
    i=i+1

* 
* * 
* * * 
* * * * 
* * * * * 


In [48]:
n = 5
i=1
while(i<=n):
    b=1
    while(b<=5-i):
        print(' ',end='')
        b=b+1
    j=1
    while(j<=i):
        print('*',end='')
        j=j+1
    print()
    i=i+1
        

    *
   **
  ***
 ****
*****


In [54]:
n=5
i=1
while(i<=5):
    b=1
    while(b<=5-i):
        print(' ',end='')
        b=b+1
    k=1
    while(j<=k):
        print('*',end='')
        j=j+1
    k=k+2
    print()
    i=i+1
    


In [56]:
n=5
i=1
k=1
while(i<=5):
    b=1
    while(b<=5-i):
        print(' ',end='')
        b=b+1
    j=1
    while(j<=k):
        print('*',end='')
        j=j+1
    k=k+2
    print()
    i=i+1
    


    *
   ***
  *****
 *******
*********
