In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]
myarry = np.array(a)
print(myarry)

[1 2 3 4 5 6]


In [3]:
type(a)

list

In [10]:
import numpy as np
a = [1,2,3,4,5,6]
myarr = np.array(a)
print(myarr)


[1 2 3 4 5 6]


In [11]:
type(a)

list

In [15]:
import numpy as np
a = [1,2,3,4,5]
myarr = np.array(a)
(myarr)

array([1, 2, 3, 4, 5])

In [16]:
type (a)

list

In [6]:
# wap to print common elements in the list
x = [1,2,3,4]
y = [5,6,7,3]
sum = []
for i in range(len(x)):
    sum.append(x[i]+y[i])
print(sum)
    
    


[6, 8, 10, 7]


In [8]:
# wap to make array with the help of user
import numpy as np
a = []
b = int(input("Enter the size of array"))
for i in range(b):
    val1 = int(input("Enter number"))
    a.append(val1)
arr = np.array(a)
arr
    

Enter the size of array6
Enter number2
Enter number3
Enter number4
Enter number5
Enter number7
Enter number8


array([2, 3, 4, 5, 7, 8])

In [9]:
import numpy as np
arr = np.array([[[1,2,3],[2,6,9],[5,4,7]]])
arr


array([[[1, 2, 3],
        [2, 6, 9],
        [5, 4, 7]]])

In [10]:
arr.ndim

3

In [11]:
arr[0]

array([[1, 2, 3],
       [2, 6, 9],
       [5, 4, 7]])

In [17]:
arr[0][2][2]



7

In [6]:
np.arange(3)

array([0, 1, 2])

In [22]:
import numpy as np
np.arange(3,20,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
x = [1,2,3,4,5,6,7]
x[0] 

1

In [25]:
x[3
 ]

4

In [39]:
x = [1,3,4,6,5,7,8]
y = [6,5,42,10,2,9]
for i in x:
    for j in y:
        if i==j:
            print("Common elements------->",j)

Common elements-------> 6
Common elements-------> 5


In [43]:
x = [1,3,4,6,5,7,8]
y = [6,5,42,10,2,9]
z=[]
for i in range(len(x)):
    z.append(x[i]+y[i])
print(z)

IndexError: list index out of range

In [45]:
x = [1,3,4,6,5,7,8]
y = [6,5,42,10,2,9]
z=[]
for i in range(len(x)):
    z.append(x[i] + y[i])
print(z)

IndexError: list index out of range

In [3]:
import numpy as np
a = int(input("Enter the size of array"))
b = []
for i in range(a):
    val1 = int(input("Enter the elemnts of the array"))
    b.append(val1)
    
arr = np.array(b)
arr


Enter the size of array4
Enter the elemnts of the array1
Enter the elemnts of the array2
Enter the elemnts of the array3
Enter the elemnts of the array5


array([1, 2, 3, 5])

In [4]:
import numpy as np
arr = np.array([[[1,2,3],[2,6,9],[5,4,7]]])
arr

array([[[1, 2, 3],
        [2, 6, 9],
        [5, 4, 7]]])

In [5]:
arr.

(1, 3, 3)

In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [9]:
arr.ndim

2

In [11]:
arr.sum()

45

In [12]:
arr.sum(axis = 0) # column wise add

array([12, 15, 18])

In [13]:
arr.sum(axis = 1) # row wise add

array([ 6, 15, 24])

In [17]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[8,2,5]]])
arr


array([[[1, 2, 3],
        [4, 5, 6],
        [8, 2, 5]]])

In [20]:
arr.sum(axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 2, 5]])

In [21]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [8, 2, 5]])

In [22]:
arr[0][2][0]

8

In [23]:
arr.sum()

36

In [25]:
arr.sum(axis=2) #row wise add ho gya

array([[ 6, 15, 15]])

In [26]:
arr.sum(axis = 1) #column wise add ho gya

array([[13,  9, 14]])

In [29]:
import numpy as np
arr = np.array([[[1,2,3]]])
arr.sum(axis = 0)

array([[1, 2, 3]])

In [30]:
arr.sum(axis = 1)

array([[1, 2, 3]])

In [31]:
arr.sum(axis = 2)

array([[6]])

In [2]:
import numpy as np
arr = np.array([[[1,2,3],[2,6,9],[5,4,7]]])
arr.size

9

In [ ]:
i