
# 1. zeros


In [6]:
import numpy as np
arr = np.zeros((3,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# 2. Ones


In [8]:
import numpy as np
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# 3.Eye


In [13]:
import numpy as np
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr.ndim

2

In [11]:
import numpy as np
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4. Diag


In [17]:
import numpy as np
arr = np.diag([[[1,2,3]]])

In [21]:
arr


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [24]:
arr.ndim

2

# 5. Randint

In [5]:
import numpy as np
arr = np.random.randint(1,10,4)
arr

array([2, 5, 4, 5])

In [6]:
import numpy as np
arr = np.random.randint(1,10,3)
arr

array([9, 3, 2])

# 6. Rand 

In [28]:
import numpy as np
arr = np.random.rand(5)
arr

array([0.33559883, 0.60820599, 0.31851091, 0.15340328, 0.16574092])

In [31]:
import numpy as np
arr = np.random.rand(2,3)
arr

array([[0.41019962, 0.29210961, 0.80843374],
       [0.50212889, 0.49340236, 0.10736327]])

In [35]:
import numpy as np
a = []
size =int(input("Enter the size of array"))
for i in range(size):
    b = int(input("Enter the elements"))
    a.append(b)
arr = np.array(a)
for i in range(arr.size):
    print(a[i])


Enter the size of array3
Enter the elements1
Enter the elements2
Enter the elements3
1
2
3


In [2]:
import numpy as np
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [7]:
import numpy as np
arr = np.random.randint(1,10,9)
arr

array([5, 2, 6, 7, 5, 9, 2, 5, 1])